=== MistoGanK/LMSGI-2024-2025/UD4_XML/ejercicio/UD4_EX2_PACK_NIKOLAY_PETKOV/ex2_2/comandas.dtd
<!ELEMENT comandas (comanda+)>
<!ELEMENT comanda (tractor+)>
<!ELEMENT tractor (components)>
<!ELEMENT components (component+)>
<!ELEMENT component (data_entrega,pes,nombre_serie,km_maxims?)>
<!ELEMENT data_entrega (dia?,mes,any)>

<!-- Declaracion de elemntos-->
<!ELEMENT pes (#PCDATA)>
<!ELEMENT nombre_serie (#PCDATA)>
<!ELEMENT km_maxims (#PCDATA)>

<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>

<!--Declaracion de atributos-->
<!ATTLIST pes unitat (quilos|grams) #REQUIRED>
<!ATTLIST component nom_fabricant CDATA #REQUIRED>
<!ATTLIST component fragil (si|no) #REQUIRED>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/ejercicio/UD4_EX2_PACK_NIKOLAY_PETKOV/ex2_2/ex2_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE comandas SYSTEM "comandas.dtd">
<comandas>

  <comanda>

    <tractor>
      <components>
        <component nom_fabricant="Lozanos.S.A" fragil="no">
          <data_entrega>
            <dia>10</dia>
            <mes>05</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="quilos">1000</pes>
          <nombre_serie>0121</nombre_serie>
          <km_maxims>120000</km_maxims>
        </component>
      </components>
    </tractor>

  </comanda>

  <comanda>

    <tractor>

      <components>

        <component nom_fabricant="Lozanos.S.A" fragil="si">
          <data_entrega>
            <mes>06</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="grams">565</pes>
          <nombre_serie>0214</nombre_serie>
        </component>

        <component nom_fabricant="Joshuas_fields.S.A" fragil="no">
          <data_entrega>
            <dia>10</dia>
            <mes>07</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="quilos">2000</pes>
          <nombre_serie>10241</nombre_serie>
        </component>

      </components>

    </tractor>

  </comanda>

  <comanda>

    <tractor> 

      <components>

        <component nom_fabricant="Joshuas_fields.S.A" fragil="si">
          <data_entrega>
            <dia>10</dia>
            <mes>10</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="grams">1450</pes>
          <nombre_serie>1924</nombre_serie>
        </component>

        <component nom_fabricant="Joshuas_fields.S.A" fragil="no">
          <data_entrega>
            <dia>12</dia>
            <mes>10</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="quilos"></pes>
          <nombre_serie>0014</nombre_serie>
          <km_maxims>23000</km_maxims>
        </component>

      </components>

    </tractor>

    <tractor>

      <components>
        <component nom_fabricant="Lozanos.S.A" fragil="si">
          <data_entrega>
            <mes>10</mes>
            <any>2025</any>
          </data_entrega>
          <pes unitat="quilos">5</pes>
          <nombre_serie>1914</nombre_serie>
        </component>
      </components>

    </tractor>

  </comanda>
</comandas>
