=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD4_PACK5_XSD/5.3/subasta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="subasta">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="objecte" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="propietari" type="xs:string"/>
              <xs:element name="preu_sortida" type="preu"/>
              <xs:element name="preu_minim" type="preu"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="preu">
    <xs:restriction base="xs:decimal">
      <xs:pattern value="\d{1,10}\.\d{2}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD4_PACK5_XSD/5.3/subasta.xml
<?xml version="1.0" encoding="UTF-8"?>
<subasta
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="subasta.xsd">
  <objecte>
    <propietari>Nikolay</propietari>
    <preu_sortida>10000.00</preu_sortida>
    <preu_minim>9000.00</preu_minim>
  </objecte>
  
  <objecte>
    <propietari>Joshua</propietari>
    <preu_sortida>10000.00</preu_sortida>
    <preu_minim>20000.00</preu_minim>
  </objecte>
</subasta>
