=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD4_PACK4_XSD/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="caÃ§alera">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="data">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:gDay" />
                    <xs:element name="mes" type="xs:gMonth" />
                    <xs:element name="any" type="xs:gYear" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="client" type="client_proveidor" />
              <xs:element name="proveidor" type="client_proveidor" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" />
          </xs:complexType>
        </xs:element>
        <xs:element name="linies">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="linia" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="article">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="descripcio" type="xs:string" />
                          <xs:element name="preus">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="amb_iva" type="preu" />
                                <xs:element name="sense_iva" type="preu" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="tipus_iva">
                            <xs:complexType>
                              <xs:attribute name="aplicat">
                                <xs:simpleType>
                                  <xs:restriction base="xs:int">
                                    <xs:enumeration value="4" />
                                    <xs:enumeration value="10" />
                                    <xs:enumeration value="21" />
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="numero_unitats" type="xs:positiveInteger"/>
                    <xs:element name="import_total" type="preu"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                  <xs:attribute name="article_ref" type="xs:IDREF" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="total">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="subtotal">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="iva4" type="preu" minOccurs="0"/>
                    <xs:element name="iva10" type="preu"/>
                    <xs:element name="iva21" type="preu"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="sense_iva" type="preu"/>
              <xs:element name="amb_iva" type="preu"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Tipus
  global client y proveidor-->
  <xs:complexType name="client_proveidor">
    <xs:attribute name="nom_fiscal" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="nom_comercial" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="nif" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string" />
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <!--Tipus
  global preus-->
  <xs:simpleType name="preu">
    <xs:restriction base="xs:decimal">
      <xs:pattern value="\d{1,10}\.\d{2}" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD4_PACK4_XSD/factura.xml
<?xml version="1.0" encoding="UFT-8"?>
<factura 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="factura.xsd">
  <caçalera id="A1">
    <data>
      <dia>---01</dia>
      <mes>--01</mes>
      <any>2025</any>
    </data>
    <client nom_fiscal="Lozano SA" nom_comercial="Lozanos y Hermanos" nif="E01512512" />
    <proveidor nom_fiscal="Erchiga SA" nom_comercial="Erchiga" nif="A9215121" />
  </caçalera>
  <linies>
    <linia id="AE3" article_ref="B1">
      <article id="B1">
        <descripcio>Armario Empotrado de Roble</descripcio>
        <preus>
          <amb_iva>10000.00</amb_iva>
          <sense_iva>8000.00</sense_iva>
        </preus>
        <tipus_iva aplicat="21" />
      </article>
      <numero_unitats>1</numero_unitats>
      <import_total>10000.00</import_total>
    </linia>
    <linia id="AE4" article_ref="B2">
      <article id="B2">
        <descripcio>Tablones de madera de roble 10 metros</descripcio>
        <preus>
          <amb_iva>100.00</amb_iva>
          <sense_iva>90.00</sense_iva>
        </preus>
        <tipus_iva aplicat="10" />
      </article>
      <numero_unitats>1000</numero_unitats>
      <import_total>10000.00</import_total>
    </linia>
  </linies>
  <total>
    <subtotal>
      <iva10>10000.00</iva10>
      <iva21>10000.00</iva21>
    </subtotal>
    <sense_iva>18500.00</sense_iva>
    <amb_iva>20000.00</amb_iva>
  </total>
</factura>
