=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/basicos/xml_externo/cars/cars.dtd
<!ELEMENT cars (car*)>
<!ELEMENT car (brand,model,type,price,info)>
<!ELEMENT info (doors,seats,itv)>

<!-- cars elements-->

<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!-- info elements -->

<!ELEMENT doors (#PCDATA)>
<!ELEMENT seats (#PCDATA)>
<!ELEMENT itv (#PCDATA)>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/basicos/xml_externo/cars/cars.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cars SYSTEM "cars.dtd">
 
 <cars>
  <car>
    <brand>Toyoya</brand>
    <model>Yaris</model>
    <type>Gasoline</type>
    <price>20.000€</price>
    <info>
      <doors>4</doors>
      <seats>4</seats>
      <itv>2024-01-01</itv>
    </info>
  </car>

  <car>
    <brand>BMW</brand>
    <model>Tornados</model>
    <type>Gasoline</type>
    <price>20.000€</price>
    <info>
      <doors>4</doors>
      <seats>4</seats>
      <itv>2024-01-01</itv>
    </info>
  </car>

 </cars>
