=== MistoGanK/LMSGI-2024-2025/UD_4_XML_SCHEMA/ejercicios/UD_4_EXERCICI_PACK_6_NIKOLAY_PETKOV/6_1/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="inici_contracte">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:gDay" />
                    <xs:element name="mes" type="xs:gMonth" />
                    <xs:element name="any" type="xs:gYear" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="ocupacio_actual" type="xs:string" />
              <xs:element name="ocupacions_posteriors" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lloc" type="xs:string" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="cap_directe" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:IDREF" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="sou">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:pattern value="\d{1,6}\.\d{2}" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="titol_academics" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulacio" type="xs:string" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="seu">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Madrid" />
                    <xs:enumeration value="Barcelona" />
                    <xs:enumeration value="Valencia" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="observacions" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="merits" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="merit" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="demerits" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="demerit" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MistoGanK/LMSGI-2024-2025/UD_4_XML_SCHEMA/ejercicios/UD_4_EXERCICI_PACK_6_NIKOLAY_PETKOV/6_1/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="empleados.xsd">
  <empleado>
    <nom id="E1">Nikolay</nom>
    <inici_contracte>
      <dia>---15</dia>
      <mes>--01</mes>
      <any>2025</any>
    </inici_contracte>
    <ocupacio_actual>Ingeniero de datos Junior </ocupacio_actual>
    <cap_directe id="E10"/>
    <sou>2000.40</sou>
    <titol_academics>
      <titulacio>Técnico Superior en Desarrollo de Aplicaciones Web</titulacio>
    </titol_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Puntualidad</merit>
        <merit>Actitud</merit>
        <merit>Trabajador</merit>
      </merits>
      <demerits>
        <demerit>Falta de compresión lectora ocasionales</demerit>
      </demerits>
    </observacions>
  </empleado>
  <empleado>
    <nom id="E2">Joshua</nom>
    <inici_contracte>
      <dia>---15</dia>
      <mes>--05</mes>
      <any>2023</any>
    </inici_contracte>
    <ocupacio_actual>Ingeniero de datos Semi-Senior</ocupacio_actual>
    <ocupacions_posteriors>
      <lloc>Ingeniero de robotica industrial Senior</lloc>
    </ocupacions_posteriors>
    <cap_directe id="E10"/>
    <sou>9000.00</sou>
    <titol_academics>
      <titulacio>Técnico Superior en Robótica Industrial</titulacio>
      <titulacio>Técnico Superior en Desarrollo de Aplicaciones Web</titulacio>
    </titol_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Amplia experiencia en Robotica</merit>
        <merit>Observador</merit>
        <merit>Puntualidad</merit>
        <merit>Trabajador</merit>
      </merits>
    </observacions>
  </empleado>
  <empleado>
    <nom id="E10">Enrique</nom>
    <inici_contracte>
      <dia>---20</dia>
      <mes>--02</mes>
      <any>2019</any>
    </inici_contracte>
    <ocupacio_actual>Desarollador de Big Data Senior</ocupacio_actual>
    <ocupacions_posteriors>
      <lloc>Desarollador de Bases de Datos Senior</lloc>
      <lloc>Desarollador de Big Data Semi-Senior</lloc>
    </ocupacions_posteriors>
    <sou>20000.00</sou>
    <titol_academics>
      <titulacio>Graduado en Ingeniería de Tecnologías de Telecomunicación</titulacio>
      <titulacio>Máster en Ingeniería de Telecomunicaciones</titulacio>
    </titol_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Liderazgo</merit>
        <merit>Enseñanza</merit>
        <merit>Visión de Proyecto</merit>
      </merits>
      <demerits>
        <demerit>Ocacionalmente fechas de entrega poco realistas a su equipo</demerit>
      </demerits>
    </observacions>
  </empleado>
  <empleado>
    <nom id="A10">Irene</nom>
    <inici_contracte>
      <dia>---10</dia>
      <mes>--03</mes>
      <any>2019</any>
    </inici_contracte>
    <ocupacio_actual>Desarolladora de Software Senior</ocupacio_actual>
    <ocupacions_posteriors>
      <lloc>Desarolladora de Software Semi-Senior</lloc>
    </ocupacions_posteriors>
    <sou>20000.00</sou>
    <titol_academics>
      <titulacio>Graduada en Ingeniería Informática</titulacio>
      <titulacio>Máster en Desarrollo de Software</titulacio>
    </titol_academics>
    <seu>Barcelona</seu>
    <observacions>
      <merits>
        <merit>Exigencia</merit>
        <merit>Buena formación al personal a cargo</merit>
        <merit>Liderazgo</merit>
      </merits>
      <demerits>
        <demerit>Ocaionalmente falta de directrices concretas en algunos proyectos</demerit>
      </demerits>
    </observacions>
  </empleado>
  <empleado>
    <nom id="A2">Sam</nom>
    <inici_contracte>
      <dia>---03</dia>
      <mes>--01</mes>
      <any>2025</any>
    </inici_contracte>
    <ocupacio_actual>Desarollador de Software Junior</ocupacio_actual>
    <cap_directe id="A10"/>
    <sou>2000.00</sou>
    <titol_academics>
      <titulacio>Técnico Superior en Desarrollo de Aplicaciones Web</titulacio>
    </titol_academics>
    <seu>Barcelona</seu>
    <observacions>
      <merits>
        <merit>Rapida compreción de nuevo conceptos</merit>
        <merit>Agilidad en resolución de problemas</merit>
      </merits>
      <demerits>
        <demerit>Ocasionalmente no deja explicar a sus superiores</demerit>
        <demerit>Puntualidad</demerit>
      </demerits>
    </observacions>
  </empleado>
</empleados>
