=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD_4_PACK6_XSD/6.1/empleats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleats">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleat" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string" />
              <xs:element name="data_inici">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:gDay" />
                    <xs:element name="mes" type="xs:gMonth" />
                    <xs:element name="any" type="xs:gYear" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="lloc_ocupa" type="xs:string" />
              <xs:element name="llocs_ocupats" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="lloc" type="xs:string" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="nomina">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:pattern value="\d{1,10}\.\d{2}" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="tituls_academics" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titul" type="xs:string" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="seu">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Madrid" />
                    <xs:enumeration value="Barcelona" />
                    <xs:enumeration value="Valencia" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="observacions" minOccurs="0">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="merits" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="merit" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="demerits" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="demerit" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required" />
            <xs:attribute name="cap" type="xs:IDREF" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD_4_PACK6_XSD/6.1/empleats.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleats
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="empleats.xsd">
  <empleat id="E1" cap="E10">
    <nom>Nikolay</nom>
    <data_inici>
      <dia>---15</dia>
      <mes>--01</mes>
      <any>2025</any>
    </data_inici>
    <lloc_ocupa>Ingeniero de datos Junior </lloc_ocupa>
    <nomina>2000.40</nomina>
    <tituls_academics>
      <titul>Técnico Superior en Desarrollo de Aplicaciones Web</titul>
    </tituls_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Puntualidad</merit>
        <merit>Actitud</merit>
        <merit>Trabajador</merit>
      </merits>
      <demerits>
        <demerit>Falta de compresión lectora ocasionales</demerit>
      </demerits>
    </observacions>
  </empleat>
  <empleat id="E2" cap="E10">
    <nom>Joshua</nom>
    <data_inici>
      <dia>---15</dia>
      <mes>--05</mes>
      <any>2023</any>
    </data_inici>
    <lloc_ocupa>Ingeniero de datos Semi-Senior</lloc_ocupa>
    <llocs_ocupats>
      <lloc>Ingeniero de robotica industrial Senior</lloc>
    </llocs_ocupats>
    <nomina>9000.00</nomina>
    <tituls_academics>
      <titul>Técnico Superior en Robótica Industrial</titul>
      <titul>Técnico Superior en Desarrollo de Aplicaciones Web</titul>
    </tituls_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Amplia experiencia en Robotica</merit>
        <merit>Observador</merit>
        <merit>Puntualidad</merit>
        <merit>Trabajador</merit>
      </merits>
    </observacions>
  </empleat>
  <empleat id="E10">
    <nom>Enrique</nom>
    <data_inici>
      <dia>---20</dia>
      <mes>--02</mes>
      <any>2019</any>
    </data_inici>
    <lloc_ocupa>Desarollador de Big Data Senior</lloc_ocupa>
    <llocs_ocupats>
      <lloc>Desarollador de Bases de Datos Senior</lloc>
      <lloc>Desarollador de Big Data Semi-Senior</lloc>
    </llocs_ocupats>
    <nomina>20000.00</nomina>
    <tituls_academics>
      <titul>Graduado en Ingeniería de Tecnologías de Telecomunicación</titul>
      <titul>Máster en Ingeniería de Telecomunicaciones</titul>
    </tituls_academics>
    <seu>Valencia</seu>
    <observacions>
      <merits>
        <merit>Liderazgo</merit>
        <merit>Enseñanza</merit>
        <merit>Visión de Proyecto</merit>
      </merits>
      <demerits>
        <demerit>Ocacionalmente fechas de entrega poco realistas a su equipo</demerit>
      </demerits>
    </observacions>
  </empleat>
  <empleat id="A10">
    <nom>Irene</nom>
    <data_inici>
      <dia>---10</dia>
      <mes>--03</mes>
      <any>2019</any>
    </data_inici>
    <lloc_ocupa>Desarolladora de Software Senior</lloc_ocupa>
    <llocs_ocupats>
      <lloc>Desarolladora de Software Semi-Senior</lloc>
    </llocs_ocupats>
    <nomina>20000.00</nomina>
    <tituls_academics>
      <titul>Graduada en Ingeniería Informática</titul>
      <titul>Máster en Desarrollo de Software</titul>
    </tituls_academics>
    <seu>Barcelona</seu>
    <observacions>
      <merits>
        <merit>Exigencia</merit>
        <merit>Buena formación al personal a cargo</merit>
        <merit>Liderazgo</merit>
      </merits>
      <demerits>
        <demerit>Ocaionalmente falta de directrices concretas en algunos proyectos</demerit>
      </demerits>
    </observacions>
  </empleat>
  <empleat id="A2" cap="A10">
    <nom>Sam</nom>
    <data_inici>
      <dia>---03</dia>
      <mes>--01</mes>
      <any>2025</any>
    </data_inici>
    <lloc_ocupa>Desarollador de Software Junior</lloc_ocupa>
    <nomina>2000.00</nomina>
    <tituls_academics>
      <titul>Técnico Superior en Desarrollo de Aplicaciones Web</titul>
    </tituls_academics>
    <seu>Barcelona</seu>
    <observacions>
      <merits>
        <merit>Rapida compreción de nuevo conceptos</merit>
        <merit>Agilidad en resolución de problemas</merit>
      </merits>
      <demerits>
        <demerit>Ocasionalmente no deja explicar a sus superiores</demerit>
        <demerit>Puntualidad</demerit>
      </demerits>
    </observacions>
  </empleat>
</empleats>
