=== MistoGanK/LMSGI-2024-2025/UD4_XML/ejercicio/UD_4_EX3_PACK_NIKOLAY_PETKOV/ex.3.4.dtd
<!ELEMENT llistat (futurs+,divises+,bons+,lletres+)>
<!ELEMENT futurs (futur+)>
<!ELEMENT futur (procedencia,valor_esperat,mercat?)>
<!ELEMENT divises (divisa+)>
<!ELEMENT bons (bon+)>
<!ELEMENT bon (procedencia,pais_de_procedencia)>
<!ELEMENT pais_de_procedencia (estat,valor_desitjat,valor_minim,valor_maxim)>
<!ELEMENT lletres (lletra+)>

<!ELEMENT divisa (procedencia,canvis?)>
<!ELEMENT canvis (canvi+)>
<!ELEMENT lletra (procedencia,pais_emisor)>

<!ELEMENT valor_esperat (#PCDATA)>
<!ELEMENT estat (#PCDATA)>
<!ELEMENT valor_desitjat (#PCDATA)>
<!ELEMENT valor_minim (#PCDATA)>
<!ELEMENT valor_maxim (#PCDATA)>
<!ELEMENT canvi (#PCDATA)>
<!ELEMENT tipo_interes (#PCDATA)>
<!ELEMENT procedencia EMPTY>
<!ELEMENT mercat EMPTY>
<!ELEMENT pais_emisor EMPTY>


<!ATTLIST futur preu CDATA #REQUIRED >
<!ATTLIST divisa preu CDATA #REQUIRED >
<!ATTLIST bon preu CDATA #REQUIRED >
<!ATTLIST lletra preu CDATA #REQUIRED >
<!ATTLIST divisa nom CDATA #REQUIRED >

<!ATTLIST procedencia capital (Madrid|Nova_York|Frankfurt|Toquio) #REQUIRED >
<!ATTLIST mercat pais (Espanya|EUA|Alemanya|Japo) #REQUIRED >
<!ATTLIST pais_emisor pais (Espanya|EUA|Alemanya|Japo) #REQUIRED >
<!ATTLIST pais_emisor tipo_interes CDATA #REQUIRED >
<!ATTLIST divisa estable (si|no) #IMPLIED >
<!ATTLIST bon estable (si|no) #IMPLIED >

=== MistoGanK/LMSGI-2024-2025/UD4_XML/ejercicio/UD_4_EX3_PACK_NIKOLAY_PETKOV/ex3.4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE llistat SYSTEM "ex.3.4.dtd">

<llistat>
    <futurs>
        <futur preu="100">
            <procedencia capital="Madrid"/>
            <valor_esperat>120</valor_esperat>
            <mercat pais="Espanya"/>
        </futur>
        <futur preu="200">
            <procedencia capital="Toquio"/>
            <valor_esperat>250</valor_esperat>
            <mercat pais="Japo"/>
        </futur>
        <futur preu="300">
            <procedencia capital="Nova_York"/>
            <valor_esperat>400</valor_esperat>
        </futur>
    </futurs>
    <divises>
        <divisa preu="200" nom="USD" estable="si">
            <procedencia capital="Madrid"/>
            <canvis>
                <canvi>EUR</canvi>
                <canvi>JPY</canvi>
                <canvi>CAD</canvi>
            </canvis>
        </divisa>
        <divisa preu="300" nom="EUR">
            <procedencia capital="Madrid"/>
        </divisa>
    </divises>
    <bons>
     <bon preu="300" estable="si">
        <procedencia capital="Frankfurt"/>
        <pais_de_procedencia>
            <estat>Alemania</estat>
            <valor_desitjat>400</valor_desitjat>
            <valor_minim>350</valor_minim>
            <valor_maxim>450</valor_maxim>
        </pais_de_procedencia>
     </bon>
    <bon preu="200" estable="no">
        <procedencia capital="Madrid"/>
        <pais_de_procedencia>
            <estat>Brazil</estat>
            <valor_desitjat>350</valor_desitjat>
            <valor_minim>150</valor_minim>
            <valor_maxim>500</valor_maxim>
        </pais_de_procedencia>
    </bon>
    </bons>
    <lletres>
        <lletra preu="300">
            <procedencia capital="Madrid"/>
            <pais_emisor pais="Espanya" tipo_interes="8%"></pais_emisor>
        </lletra>
        <lletra preu="400">
            <procedencia capital="Toquio"/>
            <pais_emisor pais="Japo" tipo_interes="10%"/>
        </lletra>
    </lletres>
    
</llistat>
