=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD_4_PACK1/1.2/carta.dtd
<!ELEMENT carta (plato)*>
  <!ELEMENT plato (nombre,precio,descripcion,calorias)>
  
  <!--DeclaraciÃ³n de los elementos-->
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT precio (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT calorias (#PCDATA)>

  <!ATTLIST precio moneda CDATA #REQUIRED>

=== MistoGanK/LMSGI-2024-2025/UD4_XML/practica/UD_4_PACK1/1.2/carta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE carta[
  <!ELEMENT carta (plato)*>
  <!ELEMENT plato (nombre,precio,descripcion,calorias)>
  
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT precio (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT calorias (#PCDATA)>

  <!ATTLIST precio moneda CDATA #REQUIRED>
]> -->
<!DOCTYPE carta SYSTEM "carta.dtd">
<carta>
  <plato>
    <nombre>Vegetal de pollo</nombre>
    <precio moneda="€">6.95</precio>
    <descripcion>Un puto vegetal de pollo que esperas leer</descripcion>
    <calorias>0 mi rey</calorias>
  </plato>
  <plato>
    <nombre>Vegetal de atún</nombre>
    <precio moneda="€">5.95</precio>
    <descripcion>Enserio tio?</descripcion>
    <calorias>-10</calorias>
  </plato>

</carta>
