=== MistoGanK/LMSGI-2024-2025/UD_4_XML_SCHEMA/ejercicios/UD_4_EXERCICIS_PACK_4_XSD/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="capÃ§alera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="data">
                                <xs:complexType>
                                    <xs:attribute name="dia" type="xs:int" use="required"/>
                                    <xs:attribute name="mes" type="xs:int" use="required"/>
                                    <xs:attribute name="any" type="xs:int" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="client">
                                <xs:complexType>
                                    <xs:attribute name="nom_fiscal" use="required"/>
                                    <xs:attribute name="nom_comercial" use="required"/>
                                    <xs:attribute name="nif" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="proveidor">
                                <xs:complexType>
                                    <xs:attribute name="nom_fiscal" use="required"/>
                                    <xs:attribute name="nom_comercial" use="required"/>
                                    <xs:attribute name="nif" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="id" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="linia" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="article">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="descripcio" type="xs:string"/>
                                        <xs:element name="preus">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="sense_iva" type="xs:double"/>
                                                    <xs:element name="amb_iva" type="xs:double"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tipu_iva">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:enumeration value="4"/>
                                                    <xs:enumeration value="10"/>
                                                    <xs:enumeration value="21"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                     </xs:sequence>
                                     <xs:attribute name="id" type="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="num_unitats" type="xs:double"/>
                            <xs:element name="import_total" type="xs:double"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:IDREF" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resum_total">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subtotal">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="iva_4" type="xs:double"></xs:element>
                                        <xs:element name="iva_10" type="xs:double"></xs:element>
                                        <xs:element name="iva_21" type="xs:double"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="total_sense_iva" type="xs:double"/>
                            <xs:element name="total_amb_iva" type="xs:double"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--Definir los typos repetidos-->
    <xs:simpleType name="id">
        <xs:restriction base="xs:ID"/>
    </xs:simpleType>

    <xs:simpleType name="nom_fiscal">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="nom_comercial">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:simpleType name="nif">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

</xs:schema>

=== MistoGanK/LMSGI-2024-2025/UD_4_XML_SCHEMA/ejercicios/UD_4_EXERCICIS_PACK_4_XSD/factura_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xs:noNamespaceSchemaLocation="factura.xsd">

        <capçalera id="F4">
        <data dia="05" mes="05" any="2025"/>
        <client nom_fiscal="Decatlonh" nom_comercial="Decatlonh SAU" nif="E93591293"/>
        <proveidor nom_fiscal="Fisitek" nom_comercial="Fisitek SAU" nif="A73291256"/>
    </capçalera>
    <linia id="E9" article_ref="A8">
        <article id="A8">
            <descripcio>Balones de basket BBASKET</descripcio>
            <preus>
                <sense_iva>50</sense_iva>
                <amb_iva>61</amb_iva>
            </preus>
            <tipu_iva aplicat="21"/>
        </article>
        <num_unitats>100</num_unitats>
        <import_total>6100</import_total>
    </linia>
    <linia id="E10" article_ref="A10">
        <article id="A10">
            <descripcio>Pelotas de tenis TK</descripcio>
            <preus>
                <sense_iva>10</sense_iva>
                <amb_iva>11</amb_iva>
            </preus>
            <tipu_iva aplicat="10"/>
        </article>
        <num_unitats>1000</num_unitats>
        <import_total>11000</import_total>
    </linia>
    <linia id="E11" article_ref="A11">
        <article id="A11">
            <descripcio>Pelotas de futbol FBK</descripcio>
            <preus>
                <sense_iva>10</sense_iva>
                <amb_iva>10.4</amb_iva>
            </preus>
            <tipu_iva aplicat="4"/>
        </article>
        <num_unitats>100</num_unitats>
        <import_total>1000.4</import_total>
    </linia>
    <resum_total>
        <subtotal>
            <iva_4>1000.4</iva_4>
            <iva_10>11000</iva_10>
            <iva_21>6100</iva_21>
        </subtotal>
        <total_sense_iva>11600.04</total_sense_iva>
        <total_amb_iva>11700.04</total_amb_iva>
    </resum_total>

    
</factura>

=== MistoGanK/LMSGI-2024-2025/UD_4_XML_SCHEMA/ejercicios/UD_4_EXERCICIS_PACK_4_XSD/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xs:noNamespaceSchemaLocation="factura.xsd">

    <capçalera id="F4">
        <data dia="05" mes="05" any="2025"/>
        <client nom_fiscal="JaimeLozano" nom_comercial="lozano SA" nif="E93591293"/>
        <proveidor nom_fiscal="Erchiga" nom_comercial="Erchiga SA" nif="A93291256"/>
    </capçalera>
    <linia id="E9" article_ref="A8">
        <article id="A8">
            <descripcio>Armario Empotrado Emporium</descripcio>
            <preus>
                <sense_iva>1000.00</sense_iva>
                <amb_iva>1100.00</amb_iva>
            </preus>
            <tipu_iva aplicat="10"/>
        </article>
        <num_unitats>1</num_unitats>
        <import_total>1100</import_total>
    </linia>
    <resum_total>
        <subtotal>
            <iva_4>0</iva_4>
            <iva_10>1100</iva_10>
            <iva_21>0</iva_21>
        </subtotal>
        <total_sense_iva>1000</total_sense_iva>
        <total_amb_iva>1100</total_amb_iva>
    </resum_total>
    
</factura>
